"""created country table 

Revision ID: 1d0d391637e0
Revises: 2aae5118a45e
Create Date: 2025-01-28 13:01:54.545999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0d391637e0'
down_revision = '2aae5118a45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_games_category_id_categories'), 'categories', ['category_id'], ['category_id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_players_country_id_countries'), 'countries', ['country_id'], ['country_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_players_country_id_countries'), type_='foreignkey')
        batch_op.drop_column('country_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('countries')
    op.drop_table('categories')
    # ### end Alembic commands ###
