"""removed genre

Revision ID: 7a1d5c555954
Revises: 1d0d391637e0
Create Date: 2025-01-28 13:05:56.015785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1d5c555954'
down_revision = '1d0d391637e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('genre')

    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_games', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
